In [1]:
import pandas as pd
import numpy as np

Load Dataset

In [2]:
df = pd.read_csv('internship_applications_dirty_dataset.csv')

In [3]:
df.head()

,Applicant_ID,Name,Age,Gender,Skills,CGPA,Experience_Years
0,96,Richard Duarte,24.0,FEMALE,Machine Learning,3.35,1
1,16,Erica Atkinson,26.0,FEMALE,Power BI,2.33,3
2,31,Sean Mitchell,27.0,Female,Excel,2.75,1
3,159,Terri Jarvis,23.0,Male,Excel,2.38,5
4,129,Robert Davis,22.0,female,Tableau,3.67,3

In [4]:
df.info

<bound method DataFrame.info of      Applicant_ID            Name   Age  Gender            Skills  CGPA  \
0              96  Richard Duarte  24.0  FEMALE  Machine Learning  3.35
1              16  Erica Atkinson  26.0  FEMALE          Power BI  2.33
2              31   Sean Mitchell  27.0  Female             Excel  2.75
3             159    Terri Jarvis  23.0    Male             Excel  2.38
4             129    Robert Davis  22.0  female           Tableau  3.67
..            ...             ...   ...     ...               ...   ...
195           107     Janice Love  20.0  FEMALE            Python  3.79
196            15    Diane Taylor  29.0  FEMALE               SQL  3.22
197            93     Sarah Scott   NaN    male     Communication  3.33
198           180  Ricardo Vaughn  29.0    MALE           Tableau  2.88
199           103     John Martin  28.0    male          Power BI  3.61

     Experience_Years
0                   1
1                   3
2                   1
3                   5
4                   3
..                ...
195                 0
196                 1
197                 0
198                 3
199                 1

[200 rows x 7 columns]>

In [5]:
df.describe()

       Applicant_ID         Age        CGPA  Experience_Years
count    200.000000  183.000000  200.000000        200.000000
mean      95.205000   24.065574    3.083500          2.660000
std       55.642822    5.408181    0.799956          2.586086
min        1.000000    5.000000   -1.500000         -2.000000
25%       46.750000   21.000000    2.577500          1.000000
50%       95.500000   24.000000    3.110000          3.000000
75%      142.250000   27.000000    3.532500          4.000000
max      192.000000   75.000000    9.800000         30.000000

Handle Missing Values

In [6]:
df.isnull().sum()

Applicant_ID         0
Name                 0
Age                 17
Gender               0
Skills              10
CGPA                 0
Experience_Years     0
dtype: int64

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [8]:
df['Skills'] =df['Skills'].fillna(df['Skills'].mode()[0])

Remove Duplicates

In [9]:
df.duplicated().sum()

np.int64(8)

In [10]:
df = df.drop_duplicates()

Detect Outliers

In [11]:
Q1 = df['CGPA'].quantile(0.25)
Q3 = df['CGPA'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['CGPA'] < lower_bound) | (df['CGPA'] > upper_bound)]

In [12]:
df = df[(df['CGPA'] >= lower_bound) & (df['CGPA'] <= upper_bound)]

Standardize Data

In [14]:
df['Gender'] = df['Gender'].str.capitalize()

In [15]:
df

,Applicant_ID,Name,Age,Gender,Skills,CGPA,Experience_Years
0,96,Richard Duarte,24.000000,Female,Machine Learning,3.35,1
1,16,Erica Atkinson,26.000000,Female,Power BI,2.33,3
2,31,Sean Mitchell,27.000000,Female,Excel,2.75,1
3,159,Terri Jarvis,23.000000,Male,Excel,2.38,5
4,129,Robert Davis,22.000000,Female,Tableau,3.67,3
...,...,...,...,...,...,...,...
195,107,Janice Love,20.000000,Female,Python,3.79,0
196,15,Diane Taylor,29.000000,Female,SQL,3.22,1
197,93,Sarah Scott,24.065574,Male,Communication,3.33,0
198,180,Ricardo Vaughn,29.000000,Male,Tableau,2.88,3
199,103,John Martin,28.000000,Male,Power BI,3.61,1

In [16]:
df['Name'] = df['Name'].str.strip()

In [17]:
df.dtypes

Applicant_ID          int64
Name                 object
Age                 float64
Gender               object
Skills               object
CGPA                float64
Experience_Years      int64
dtype: object

In [18]:
df['Age'] =df['Age'].astype(int)

In [19]:
df['Experience_Years'] = df['Experience_Years'].apply(lambda x: 'Yes' if x > 0 else 'No')

In [21]:
print(df)

     Applicant_ID            Name  Age  Gender            Skills  CGPA  \
0              96  Richard Duarte   24  Female  Machine Learning  3.35
1              16  Erica Atkinson   26  Female          Power BI  2.33
2              31   Sean Mitchell   27  Female             Excel  2.75
3             159    Terri Jarvis   23    Male             Excel  2.38
4             129    Robert Davis   22  Female           Tableau  3.67
..            ...             ...  ...     ...               ...   ...
195           107     Janice Love   20  Female            Python  3.79
196            15    Diane Taylor   29  Female               SQL  3.22
197            93     Sarah Scott   24    Male     Communication  3.33
198           180  Ricardo Vaughn   29    Male           Tableau  2.88
199           103     John Martin   28    Male          Power BI  3.61

    Experience_Years
0                Yes
1                Yes
2                Yes
3                Yes
4                Yes
..               ...
195               No
196              Yes
197               No
198              Yes
199              Yes

[190 rows x 7 columns]

In [22]:
df.to_csv('internship_applications_cleaned_dataset.csv', index=False)